#!/bin/sh

DEFAULT_COVER="/home/herold/.config/mpd/defaultcover.gif"
PREVCOVER="/home/herold/.config/mpd/blackpixel.png"
MUSICDIR="/home/herold/music"

firstloop=true

while true; do

  # Exit if meh is closed
  if [ $firstloop = false ]; then
    pgrep meh > /dev/null || exit
  fi

  MFILE=$(mpc current -f %file%)
  MFILE=${MFILE%/*}
  MFILE=${MFILE%/$}

  FULLDIR="$MUSICDIR/$MFILE"

  [ -n "$FULLDIR" ] && COVERS=`ls "$FULLDIR" | grep "\.jpg\|\.png\|\.gif"`

  if [ -z "$COVERS" ]; then
    COVERS="$DEFAULT_COVER"
  else
    TRYCOVERS=`echo "$COVERS" | grep -i "cover\|front\|folder\|albumart" | head -n 1`

    if [ -z "$TRYCOVERS" ]; then
      TRYCOVERS=`echo "$COVERS" | head -n 1`
      if [ -z "$TRYCOVERS" ]; then
        TRYCOVERS="$DEFAULT_COVER"
      else
        TRYCOVERS="$FULLDIR/$TRYCOVERS"
      fi
    else
      TRYCOVERS="$FULLDIR/$TRYCOVERS"
    fi

    COVERS="$TRYCOVERS"
  fi

  if [ "$COVERS" != "$PREVCOVER" ]; then
    PREVCOVER=$COVERS
    echo "$COVERS"
  fi

  sleep 1

  firstloop=false

done | meh -ctl
