#!/bin/bash

source $(dirname $0)/panel.cfg

dzenpid=$(cat $DSLIDER_PID)
dzenpid="${dzenpid:2}"

if [ $1 == "Mu" ]; then # The music popup is NOT a slider, so it must be treated separately
  title="Music"
  message=" ^ca(1,$(dirname $0)/coverart)^fg($DZEN_FG_URGENT)^ca()^ca(1,$(dirname $0)/run-or-raise ncmpcpp &)^fg($DZEN_FG_ICON)^ca()   "
else
  case $1 in
    Vl) # Master volume
      currentValue=$(amixer -q | grep -A5 Master | grep '%' | cut -d'[' -f2 | cut -d'%' -f1)
      maxValue=100
      title="^ca(1,amixer set Master 0 ; pkill not-stat ; $(dirname $0)/not-stat $1 &)Master^ca()"
      ;;
  esac

  currentValue=$(($currentValue*10/$maxValue))

  ## MAKE THE SLIDER ##
  slider="^fg($DZEN_FG_SELECTED)"
  for i in {1..10}
  do
    # Add the command to change the value
    slider+="^ca(1,"
    case $1 in
      Vl) # PCM channel volume
        slider+="amixer set Master $(($i*$maxValue/10))% > /dev/null"
        ;;
    esac
    slider+=" ; $(dirname $0)/dslider-content $1 ; pkill not-stat ; $(dirname $0)/not-stat $1 &)"

    # Draw the slider
    #  The special characters $full_slider, $indicator_slider
    # and $empty_slider are configured in 'panel-settings'
    if [ "$i" -gt "$currentValue" ]; then
      slider+="$DSLIDER_EMPTY"
    elif [ "$i" -eq "$currentValue" ]; then
      slider+="$DSLIDER_INDICATOR^fg($FG_EMPTY)"
    else
      slider+="$DSLIDER_FULL"
    fi

    # Finish the value changing command
    slider+="^ca()"
  done
  slider+="^fg()"

  message=$slider
fi

# Add close button and send the message to the fifo read by dzen
echo " $title $message  ^ca(1,$(dirname $0)/dslider close)^fg($DZEN_FG_CLOSE)^fg()^ca()" > $DSLIDER_FIFO
