#!/bin/sh
case $1 in
  thunar)
    pgrep -f "thunar" > /dev/null && wmctrl -a "- File Manager" || thunar
    ;;
  transmission)
    pid=$(pgrep -o -f "termite -e transmission-remote-cli")
    wid=$(xdo id -p "$pid" | head -n 1)
    pgrep -f "termite -e transmission-remote-cli" > /dev/null && wmctrl -i -a "$wid" || termite -e transmission-remote-cli
    ;;
  ncmpcpp)
    pid=$(pgrep -o -f "termite -e ncmpcpp")
    wid=$(xdo id -p "$pid" | head -n 1)
    pgrep -f "termite -e ncmpcpp" > /dev/null && wmctrl -i -a "$wid" || termite -e ncmpcpp
    ;;
  mutt)
    pid=$(pgrep -o -f "termite -e mutt-panel")
    wid=$(xdo id -p "$pid" | head -n 1)
    pgrep -f "termite -e mutt-panel" > /dev/null && wmctrl -i -a "$wid" || termite -e mutt-panel
    ;;
  coverart)
    pgrep -f "coverart" > /dev/null && wmctrl -a "meh" || $(dirname $0)/coverart
    ;;
esac
