[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#686868"
blue = "#57c7ff"
cyan = "#9aedfe"
green = "#5af78e"
magenta = "#ff6ac1"
red = "#ff5c57"
white = "#eff0eb"
yellow = "#f3f99d"

[colors.cursor]
cursor = "#97979b"

[colors.normal]
black = "#282a36"
blue = "#57c7ff"
cyan = "#9aedfe"
green = "#5af78e"
magenta = "#ff6ac1"
red = "#ff5c57"
white = "#f1f1f0"
yellow = "#f3f99d"

[colors.primary]
background = "#282a36"
foreground = "#eff0eb"

[colors.selection]
background = "#feffff"
text = "#282a36"

[debug]
persistent_logging = false
render_timer = false

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
family = "FiraCode Nerd Font"

[keyboard]
bindings = [
  { action = "Copy",             key = "C",      mods = "Control|Shift" },
  { action = "Copy",             key = "Copy",   mods = "" },
  { action = "DecreaseFontSize", key = "Minus",  mods = "Control|Shift" },
  { action = "IncreaseFontSize", key = "Equals", mods = "Control|Shift" },
  { action = "Paste",            key = "Paste",  mods = "" },
  { action = "Paste",            key = "V",      mods = "Control|Shift" },
]

[scrolling]
history = 10000
multiplier = 3

[window]
dynamic_padding = true

[window.padding]
x = 5
y = 5
