env:
  TERM: xterm-256color

window:
  dynamic_padding: true
  padding:
    x: 5
    y: 5

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: FiraCode Nerd Font
  size: 12.0
  use_thin_strokes: true

debug:
  render_timer: false
  persistent_logging: false

draw_bold_text_with_bright_colors: true

colors:
  primary:
    background: '0x2b2b2b'
    foreground: '0xe6e1dc'
  cursor:
    text: '0x2b2b2b'
    cursor: '0xe6e1dc'
  normal:
    black:   '0x2b2b2b'
    red:     '0xda4939'
    green:   '0xa5c261'
    yellow:  '0xffc66d'
    blue:    '0x6d9cbe'
    magenta: '0xb6b3eb'
    cyan:    '0x519f50'
    white:   '0xe6e1dc'
  bright:
    black:   '0x2b2b2b'
    red:     '0xda4939'
    green:   '0xa5c261'
    yellow:  '0xffc66d'
    blue:    '0x6d9cbe'
    magenta: '0xb6b3eb'
    cyan:    '0x519f50'
    white:   '0xf9f7f3'

key_bindings:
  - { key: Paste,                         action: Paste                            }
  - { key: Copy,                          action: Copy                             }
  - { key: V,        mods: Control|Shift, action: Paste                            }
  - { key: C,        mods: Control|Shift, action: Copy                             }
  - { key: Equals,   mods: Control|Shift, action: IncreaseFontSize                 }
  - { key: Minus,    mods: Control,       action: DecreaseFontSize                 }
